### ISSUE TITLE
Module augmentation doesn't apply to useSession().data

### ISSUE THREAD

**Issue by tmlmt** [sidebase/nuxt-auth#120] opened 2022-12-23 09:10 UTC
### Environment

- Operating System: `Linux`
- Node Version:     `v16.18.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `css`, `build`, `modules`, `content`, `runtimeConfig`, `auth`
- Runtime Modules:  `@nuxt/content@2.2.2`, `@sidebase/nuxt-auth@0.3.0`
- Build Modules:    `-`

### Reproduction

1. Define a `next-auth.d.ts` as explained in the [doc](https://sidebase.io/nuxt-auth/recipes/custom-session-data#updating-typescript-interfaces-for-accurate-typing) to augment the next-auth module with custom session data:
```typescript
import NextAuth, { DefaultSession } from "next-auth";

declare module "next-auth" {
  interface Session {
    user: {
      /** The user's postal address. */
      address: string
    } & DefaultSession["user"]
  }
}
```
2. In a component, call `useSession()` and see what TypeScript suggests in the `data.value.user` value:
```typescript
const { data: session } = useSession();
session.value?.user.<cursor_position>
```

### Describe the bug

Only the default user properties are proposed, suggesting that module augmentation is not taken into account by nuxt-auth's `useSession()` composable:
![image](https://user-images.githubusercontent.com/10244927/209305299-9db112ac-88a2-4ae5-849c-e770e1309227.png)

### Additional context

Looking at `node_modules/@sidebase/nuxt-auth/dist/runtime/composables/useSession.d.ts`, the `data` property type is hardcoded to the default and not referring to SessionData.
```typescript
declare const _default: () => {
    status: import("vue").ComputedRef<"authenticated" | "unauthenticated" | "loading">;
    data: Readonly<import("vue").Ref<{
        readonly user?: {
            readonly name?: string | null | undefined;
            readonly email?: string | null | undefined;
            readonly image?: string | null | undefined;
        } | undefined;
        readonly expires: string;
    } | null | undefined>>;
//...
};
```
Replacing this by the following fixed things for me:
```typescript
declare const _default: () => {
    status: import("vue").ComputedRef<"authenticated" | "unauthenticated" | "loading">;
    data: Readonly<import("vue").Ref<SessionData>>;
//...
};
```
You can maybe trace things back to the src code, if you confirm this is a bug

**Comment by BracketJohn** [comment] 2022-12-23 12:18
Hey @tmlmt 👋 

Thanks for the issue + the thourough research you already did (: 

This is actually an issue we fixed yesterday! See https://github.com/sidebase/nuxt-auth/issues/112 and PR: #115 by @JoaoPedroAS51 💯 

I'm doing a release in a couple of minutes, would be great if you can do a clean install of that version then and check if the error persist. 

I'll let you know here when the release is done + close the issue with the release. Would mean the world if you could then still get back to me here, on discord or via a new issue to let me know if the issue is fixed ❤️

**Comment by BracketJohn** [comment] 2022-12-23 13:05
Closed by https://github.com/sidebase/nuxt-auth/releases/tag/0.3.1 🎊 

To use: `npm i -D @sidebase/nuxt-auth@0.3.1`

**Closed by BracketJohn** 2022-12-23 13:05 UTC
Labels: bug

**Comment by tmlmt** [comment] 2022-12-23 14:48
@BracketJohn, great ! I confirm it's working with v0.3.1 🎉 
As a matter of fact, the other bug I encountered earlier today was actually the other one that was fixed in the release (`redirect: false`) and it's also working like a charm.
Thanks, both of two 👍

**Comment by BracketJohn** [comment] 2022-12-23 14:57
Yaaay, glad to hear and thank you so much for reporting this back (: Happy holidays!
