### ISSUE TITLE
Not working with Credentials provider

### ISSUE THREAD

**Issue by jorgv** [sidebase/nuxt-auth#9] opened 2022-11-04 09:32 UTC
### Environment

Nuxi 3.0.0-rc.11
Nuxt 3.0.0-rc.11 with Nitro 0.5.4
@sidebase/nuxt-auth 0.0.1-beta.3

### Describe the bug

Thank you for this awesome module, it is the missing piece for the Nuxt universe.

I have try to setup nuxt-auth with the credentials Provider which is the most common type when using a decoupled backend.

this is my auth config in nuxt.config.ts copied from official docs in NextAuth

NUXT_URL =  http://localhost/api/auth/

```
  auth: {
    nextAuth: {
      url: process.env.NUXT_URL,
      options: {
        secret: process.env.NUXT_SECRET,
        providers: [
          CredentialsProvider({
            // The name to display on the sign in form (e.g. 'Sign in with...')
            name: 'Credentials',
            // The credentials is used to generate a suitable form on the sign in page.
            // You can specify whatever fields you are expecting to be submitted.
            // e.g. domain, username, password, 2FA token, etc.
            // You can pass any HTML attribute to the <input> tag through the object.
            credentials: {
              username: { label: 'Username', type: 'text', placeholder: 'jsmith' },
              password: { label: 'Password', type: 'password' },
            },
            async authorize(credentials, req) {
              // You need to provide your own logic here that takes the credentials
              // submitted and returns either a object representing a user or value
              // that is false/null if the credentials are invalid.
              // e.g. return { id: 1, name: 'J Smith', email: 'jsmith@example.com' }
              // You can also use the `req` object to obtain additional parameters
              // (i.e., the request IP address)
              // eslint-disable-next-line no-console
              console.log(credentials)
              const user = { id: '1', name: 'J Smith', email: 'jsmith@example.com' }

              if (user) {
                // Any object returned will be saved in `user` property of the JWT
                return user
              }
              else {
                // If you return null then an error will be displayed advising the user to check their details.
                return null

                // You can also Reject this callback with an Error thus the user will be sent to the error page with the error message as a query parameter
              }
            },
          }),
        ],
      },
    },
```

Login form its showing but not matter what is the input for username and password it always show the error: "Sign in failed. Check the details you provided are correct."

the authorize function its never reach when submitting the form.

Is there anything else I am missing in order to make it work

**Comment by BracketJohn** [comment] 2022-11-05 08:13
Thanks for opening the issue!

I'm on vacay, but already know what's going on and will comment that for the benefit @valiafetisov and @zoey-kaiser who may further this issue until I'm back:
- In order to setup the providers in the backend, we serialize each provider and then reconstruct it in the backend:
    - serialization: https://github.com/sidebase/nuxt-auth/blob/a1269537c721aa60aebe5e452fe3044c55fc1b6d/src/module.ts#L67-L96
    - deserialization in runtime: https://github.com/sidebase/nuxt-auth/blob/a1269537c721aa60aebe5e452fe3044c55fc1b6d/src/runtime/server/api/auth.ts#L30-L35
- The problem is that `authorize` does not de-/serialize correctly as it's a function
  - this is a known limitation / feature, as described by @danielroe:
    - https://github.com/nuxt/framework/issues/8419#issuecomment-1289287990
    - https://github.com/sidebase/nuxt-auth/issues/1#issuecomment-1293378274
- we need to find a way to pass authorize to the runtime (this would also enable a lot of other stuff). Options I already know of:
  - some sort of de-/serialize for non-0natively serializable things
  - change the module so that the user creates their own endpoint files in their codebase, where their config is parsed at runtime, thus removing this barrier (e.g., user creates their own `/server/api/auth.ts`)

**Comment by BracketJohn** [comment] 2022-11-05 09:09
It rains a lot here atm, so I was able to open: #10 that would resolve this and basically bring us onto feature parity with next-auth.js a lot quicker!

**Comment by BracketJohn** [comment] 2022-11-07 01:25
@jorgv  checkout 0.0.1-beta.4 -> credentials flow should work. Please give feedback here (: 

@zoey-kaiser please update the nuxt auth demo!

**Comment by BracketJohn** [comment] 2022-11-07 15:17
Hey @jorgv we got the credentials flow working with our nuxt auth demo app, check it out! Link is on main page of repo.

Please let me know if it works for you now, so thst we can close this issue (:

**Comment by jorgv** [comment] 2022-11-07 20:59
Hey guys I will test them and get back to you

**Comment by jorgv** [comment] 2022-11-07 21:57
@BracketJohn works perfectly! Thanks so much. I will leave my [...].ts in case someone else needs it for Credentials provider:

```
import CredentialsProvider from 'next-auth/providers/credentials'
import { NuxtAuthHandler } from '#auth'

export default NuxtAuthHandler({
  providers: [
    // @ts-expect-error Import is exported on .default during SSR, so we need to call it this way. May be fixed via Vite at some point
    CredentialsProvider.default({
      name: 'Credentials',

      credentials: {
        username: { label: 'Username', type: 'text', placeholder: 'jsmith' },
        password: { label: 'Password', type: 'password' },
      },
      async authorize(credentials, req) {
        
        // const user = { id: '1', name: 'J Smith', email: 'jsmith@example.com' }
        const token = Buffer.from(`${credentials.username}:${credentials.password}`).toString('base64')
        const res = await fetch('http://localhost/login', {
          method: 'post',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Basic ${token}`,
          },
        })
        const user = await res.json()
        // If no error and we have user data, return it
        if (res.ok && user) {
          return user
        }
        else {
          // If you return null then an error will be displayed advising the user to check their details.
          return null
          // You can also Reject this callback with an Error thus the user will be sent to the error page with the error message as a query parameter
        }
      },
    }),
  ],
})

```

**Comment by BracketJohn** [comment] 2022-11-08 00:11
Superb! Glad that it works and sure thing!

---

For future readers: In the above code sample by @jorgv the credentials are checked against a locally available service that has a /login endpoint. In your code you could replace the fetch call with a database query to get and compare known usernames and passwords, with opening a file that contains known usernames and passwords, with looking into an env variable that contains known username and password, ...

The above are jist examples to show that a lot is possible. In practice implementing a login + stpring credentials correctly often requires a lot of care, but it is also use-case specific how mich care is sctually needed. So stay safe out there!

**Closed** 2022-11-08 00:12 UTC
Labels: bug

**Comment by itsalfredakku** [comment] 2024-09-07 13:48
> @BracketJohn works perfectly! Thanks so much. I will leave my [...].ts in case someone else needs it for Credentials provider:
> 
> ```
> import CredentialsProvider from 'next-auth/providers/credentials'
> import { NuxtAuthHandler } from '#auth'
> 
> export default NuxtAuthHandler({
>   providers: [
>     // @ts-expect-error Import is exported on .default during SSR, so we need to call it this way. May be fixed via Vite at some point
>     CredentialsProvider.default({
>       name: 'Credentials',
> 
>       credentials: {
>         username: { label: 'Username', type: 'text', placeholder: 'jsmith' },
>         password: { label: 'Password', type: 'password' },
>       },
>       async authorize(credentials, req) {
>         
>         // const user = { id: '1', name: 'J Smith', email: 'jsmith@example.com' }
>         const token = Buffer.from(`${credentials.username}:${credentials.password}`).toString('base64')
>         const res = await fetch('http://localhost/login', {
>           method: 'post',
>           headers: {
>             'Content-Type': 'application/json',
>             'Authorization': `Basic ${token}`,
>           },
>         })
>         const user = await res.json()
>         // If no error and we have user data, return it
>         if (res.ok && user) {
>           return user
>         }
>         else {
>           // If you return null then an error will be displayed advising the user to check their details.
>           return null
>           // You can also Reject this callback with an Error thus the user will be sent to the error page with the error message as a query parameter
>         }
>       },
>     }),
>   ],
> })
> ```

Impressive!
