### ISSUE TITLE
[nuxt] Could not access `then`. The only available runtime config keys on the client side are `public` and `app`

### ISSUE THREAD

**Issue by gabriel-nigro** [sidebase/nuxt-auth#927] opened 2024-10-16 12:57 UTC
### Describe the feature

I'm using Sidebase Nuxt-Auth + Nuxt3 + Vuetify3, and I'm getting this annoying warning when I click on the logout button, which calls `signOut` function.

### Environment

❯ npx nuxi info
[17:08:40] Working directory: /home/projects/github-dvjyh3
[17:08:40] Nuxt project info: 

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.13.2
- CLI Version:      3.14.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

[Link to stackblitz.](https://stackblitz.com/edit/github-dvjyh3)

Just go to `/login` page and sign in. Right before you'll be redirected to `/home`, which have sign out button. Open console and click the button.

### Provider

- [ ] AuthJS
- [X] Local
- [ ] Refresh
- [ ] New Provider

### Logs

Warning in Console:

> [nuxt] Could not access `then`. The only available runtime config keys on the client side are `public` and `app`. See https://nuxt.com/docs/guide/going-further/runtime-config for more information.

**Comment by andrescellini** [comment] 2024-10-19 22:36
having same warning with both signIn and signOut methods using local provider

**Comment by carvalhoms** [comment] 2024-11-28 21:27
Hello, same issue here. I just created a new Nuxt application, imported nuxt-auth, and used the basic local provider setup as described in the documentation, but I'm encountering the same warning:

[nuxt] Could not access 'then'. The only available runtime config keys on the client side are 'public' and 'app'.

nuxt-auth 0.9.4

Has anyone figured out what’s causing this?

Will this cause issues in production?

**Comment by phoenix-ru** [comment] 2024-12-12 16:50
I was finally able to reproduce this warning. It was caused by a flaky behaviour of Nuxt trying to Proxy the Runtime Config. Doing an `await` on `runtimeConfig` caused Nuxt to issue the warning. There should be no problem in production though.

Will be fixed in #942 as it is trivial.

https://github.com/sidebase/nuxt-auth/blob/f5c33262f8bcf5b73402b5293d469824da1353ef/src/runtime/utils/fetch.ts#L7

https://github.com/nuxt/nuxt/blob/4d22f4d5ace0e206c90c7e3d334a1a2394f4ecbc/packages/nuxt/src/app/nuxt.ts#L571-L580

**Closed** 2024-12-12 18:09 UTC
Labels: p3, bug
