### ISSUE TITLE
not support with i18n module

### ISSUE THREAD

**Issue by AbdullahAlfar** [sidebase/nuxt-auth#828] opened 2024-07-22 12:47 UTC
### Environment

Nuxt Version:     3.12.1

### Reproduction

https://github.com/nuxt-modules/i18n

### Describe the bug

pages: {
        login: '/ar/signin'
      },
we need to make the redirect detect by language chosen

**Comment by zoey-kaiser** [comment] 2024-07-22 15:57
Duplicate of #722

**Closed by zoey-kaiser** 2024-07-22 15:57 UTC
Labels: bug, pending
