### ISSUE TITLE
Allow the `useSession` composable name to be dynamic

### ISSUE THREAD

**Issue by agracia-foticos** [sidebase/nuxt-auth#177] opened 2023-01-23 12:07 UTC
### Environment

- Operating System: `Linux`
- Node Version:     `v18.13.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.19.3`
- Builder:          `vite`
- User Config:      `srcDir`, `modules`, `tailwindcss`, `vite`, `schemaOrg`, `telemetry`, `algolia`, `head`, `auth`, `viewport`, `css`, `build`, `runtimeConfig`
- Runtime Modules:  `genesis-design-system/nuxt`, `@nuxtjs/algolia@1.5.0`, `@nuxtjs/tailwindcss@6.2.0`, `formidable@2.1.1`, `nuxt-viewport@2.0.3`, `@nuxtjs/partytown@1.3.0`, `@vueuse/nuxt@9.11.1`, `@nuxtjs/i18n-edge@8.0.0-beta.4-27812700.b832f07`, `nuxt-schema-org@1.1.0-beta.6`, `nuxt-icon@0.1.8`, `@pinia/nuxt@0.4.6`, `@nuxtjs/i18n@8.0.0-beta.8`, `@sidebase/nuxt-auth@0.3.4`, `@sidebase/nuxt-session@0.2.6`
- Build Modules:    `-`

### Describe the bug

Both projects use the composable useSession... can't both coexist?

My intention is to generate a session identifier at application startup (with nuxt-session) and then handle the user info with nuxt-auth (login is not required)

**Comment by BracketJohn** [comment] 2023-01-23 17:39
Phew - could you instead use `nuxt-auth` to do both? It also sets up a unique session identifier, so if it's only that you are after, you could do that?

Also, this is not a bug, rather a question I think, so let's update the tags!

**Comment by agracia-foticos** [comment] 2023-01-24 07:01
> Phew - could you instead use `nuxt-auth` to do both? It also sets up a unique session identifier, so if it's only that you are after, you could do that?
> 
> Also, this is not a bug, rather a question I think, so let's update the tags!

I want to define a session (an identifier) ​​when starting the application (through a plugin) that is independent of being logged in or not.

That is why I would need the session component on the one hand and the login component on the other.

**Comment by BracketJohn** [comment] 2023-02-01 14:14
I see! I would not consider to rename the composable of this or the other library at the moment.

We could look into making the name of `useSession` dynamic, so that you can overwrite it for your use-case.

If you want to open a PR I would be glad to review that and get it merged. For now I won't actively push it though as there's more pressing issues for this library. I'll rename this issue and make it a feature-request (:

**Comment by agracia-foticos** [comment] 2023-02-01 14:18
> I see! I would not consider to rename the composable of this or the other library at the moment.
> 
> We could look into making the name of `useSession` dynamic, so that you can overwrite it for your use-case.
> 
> If you want to open a PR I would be glad to review that and get it merged. For now I won't actively push it though as there's more pressing issues for this library. I'll rename this issue and make it a feature-request (:

perfect, thank you very much, I am still waiting for the improvement!!!

**Comment by BracketJohn** [comment] 2023-02-01 14:30
Sure - do you maybe want to try your hand at implementing it?

**Comment by zoey-kaiser** [comment] 2023-02-20 13:46
Hi @agracia-foticos!

`h3` and therefore Nuxt have recently received custom session support 🥳! Therefore you could use `nuxt-auth` + their sessions for your use case.
We are still looking into renaming `useSession()` to `useAuth()` in the future regardless.

Thank you for your issue! If anything else arises where we can help feel free to respond back!

**Closed by zoey-kaiser** 2023-02-20 13:46 UTC
Labels: enhancement, good first issue

**Comment by tcarterBAMF** [comment] 2023-03-13 13:57
@zoey-kaiser 

I'm trying to use @sidebase/nuxt-session along side nuxt-auth, so changing the auto-imported name to match the module name would help immensely.

Is there a suggested way to use these 2 modules in the same project?
