### ISSUE TITLE
[nuxt] error in version 0.10.0-rc.2 of sidebase

### ISSUE THREAD

**Issue by DoctorNorriq** [sidebase/nuxt-auth#962] opened 2024-12-17 08:35 UTC
### Environment

- Operating System: Windows_NT
- Node Version:     v20.17.0
- Nuxt Version:     3.14.1592
- CLI Version:      3.15.0
- Nitro Version:    2.10.4
- Package Manager:  npm@10.8.2
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxtjs/i18n@8.5.6, @pinia/nuxt@0.7.0, pinia-plugin-persistedstate/nuxt, @nuxtjs/google-fonts@3.2.0, nuxt-primevue@3.0.0, nuxt-lodash@2.5.3, @vueuse/nuxt@11.3.0, @nuxtjs/device@3.2.4, nuxt-icon@0.6.10, @zadigetvoltaire/nuxt-gtm@0.0.13, @nuxt/image@1.8.1, @sidebase/nuxt-auth@0.10.0-rc.2, @nuxtjs/tailwindcss@6.12.2, @nuxt/eslint@0.7.1, @formkit/auto-animate/nuxt@0.8.2, @vueform/nuxt@1.8.0
- Build Modules:    -

### Reproduction

No minimal reproduction provided

### Describe the bug

Error when running dev server with: "@sidebase/nuxt-auth": "^0.10.0-rc.2"

![nuxt-sidebase-bug](https://github.com/user-attachments/assets/e0f1395b-9501-4118-9106-3509ed4f1120)

### Additional context

I tried switching to an earlier version of sidebase, where the problem did not persist. When I then switched back to 0.10.0-rc.2, the error was gone. The only difference I can see is a "license": "MIT" added in my package-lock.json to the node_modules/@sidebase/nuxt/auth object.

![image](https://github.com/user-attachments/assets/b7167b59-01c9-4a93-974f-dbd57fd05907)

P.s, this is my first bug report, so I hope the provided info is enough to understand the scope of the issue :)

**Comment by zoey-kaiser** [comment] 2024-12-17 08:54
Hi @DoctorNorriq 👋 
 
This is because v0.10 contains several breaking changes! I am currently finalizing the upgrade guide to make the migration easier. I can help you out here if you could share the following with me:

- Auth configuration in the `nuxt.config.ts`
- Environment variable you currently use to set the AUTH_ORIGIN

**Comment by DoctorNorriq** [comment] 2024-12-17 09:03
Cheers, Zoey!

Affirmative :)

auth: {
        isEnabled: true,
        baseURL: 'https://api.dev.accelerator.norriq.dev/api/user/',
        provider: {
            type: 'local',
            pages: {
                login: '/login',
            },
            endpoints: {
                signIn: { path: 'Login', method: 'post' },
                getSession: { path: 'GetUser' },

                signOut: { path: 'logout', method: 'get' },
            },
            refresh: {
                isEnabled: true,
                endpoint: { path: 'GetAccessToken', method: 'post' },
                token: {
                    signInResponseRefreshTokenPointer: '/refreshToken',
                },
            },
            token: {
                signInResponseTokenPointer: '/accessToken',
                maxAgeInSeconds: 60 * 5, // 5 min
                sameSiteAttribute: 'lax',
            },
        },
        sessionRefresh: {
            enableOnWindowFocus: false,
            enablePeriodically: 1 * 60 * 2 * 1000, // 2 minutes
        },
        globalAppMiddleware: {
            isEnabled: true,
        },
    },

I can't seem to find anything regarding AUTH_ORIGIN; any ideas where I might find the env var?
(will edit this part, if I find it before you answer)

**Comment by zoey-kaiser** [comment] 2024-12-17 21:03
Hi @DoctorNorriq 👋 

Sadly I cannot conclude anything else from the console error you sent over. Could you please create a minimal reproduction of the issue using this minimal `local` starter template: https://stackblitz.com/github/zoey-kaiser/nuxt-auth-starters/tree/main/starters/local?file=nuxt.config.ts

**Comment by phoenix-ru** [comment] 2024-12-19 09:21
@DoctorNorriq do you still have the error with `0.10.0-rc.2`? I think it may have been related to NPM caching rather than our module

**Comment by OlePc** [comment] 2024-12-19 09:29
@phoenix-ru I asked @DoctorNorriq to open the issue. But I agree. It seems to be an NPM issue more than an issue with the module. We need 0.10.0-rc.2, though, to be able to overwrite baseURL using an environment variable. You may close the issue 👍

**Comment by zoey-kaiser** [comment] 2024-12-19 09:51
Awsome! Great to hear 🤗

**Closed by zoey-kaiser** 2024-12-19 09:51 UTC
Labels: question
