### ISSUE TITLE
[QUESTION] Passport Local/Steam Strategies, Express Session

### ISSUE THREAD

**Issue by angelhdzmultimedia** [sidebase/nuxt-auth#187] opened 2023-01-27 07:24 UTC
### Ask your question

I've been researching a lot about auth and session, and my search brought me here.

I read that it's easy to set up, but I can't get my head to understand how to create custom strategies like Passport local and Steam.

So few questions: 

1. How to get Steam Strategy to work with sidebase/nuxt-auth's sessions?
2. How to set up strategies?
3. How to use connect-mongodb-session to persist the session? Or does this package have a native way to persist the data to MongoDB?

 Until  now I have been using NestJS for the backend. I'm excited to start working on Nuxt 3 as full stack!

Any info will be greatly appreciated.

**Comment by zoey-kaiser** [comment] 2023-01-27 08:36
Hi @angelhdzmultimedia!

Great to hear you will be working with Nuxt now! I hope you are enjoying your experience. 

We are using NextAuth under the hood and it sadly does not have support for steam out of the box (see all out of the box supported providers [here](https://next-auth.js.org/providers/))

I did some research into using OpenID (which is Steam authentication system) and sadly noticed that it seems pretty difficult (if you are not an offical steam partner). I found this issue from last year about a request to add it to NextAuth. https://github.com/nextauthjs/next-auth/discussions/697

From what I make out of the issue is that it is not as simple as it may seem. You may need to install https://sidebase.io/nuxt-session and implement the system yourself with their API https://steamcommunity.com/dev, however this seems like a bigger task. 

> How to use connect-mongodb-session to persist the session? Or does this package have a native way to persist the data to MongoDB?

I will pass this question to @BracketJohn as I don't think I can give you the best suggestion on how to handle this! 

I am sorry that I couldn't give you an amazing answer to your questions! Maybe @BracketJohn has some other ideas that can help you. Regardless I wish you the best of luck and a lot of fun with Nuxt!

**Comment by angelhdzmultimedia** [comment] 2023-01-27 20:12
> I am sorry that I couldn't give you an amazing answer to your questions!
The simple fact of using your time and energy to answer me, and even so fast, is **AMAZING**!
Thank you so much.

And I understood all about the steam auth issue. 

Maybe I will check the passport-steam package's files to see  how they implement the auth.
In my NestJS or pure Node/Express app, I have 2 controllers, 1 redirects to the steam login page, the other is the steam/return controller that has the user injected in req.user.

So any guide how to use local auth instead? 
I want to start with something easy as local auth, and then escalate to Github, Google Auth.

Excited to start trying this package. 

Wishing you all health, peace, and success.

**Comment by BracketJohn** [comment] 2023-02-08 09:26
Thank you for the nice wishes. 

If you want to start with a local auth strategy, you'lll need another package. You could look into using https://github.com/sidebase/nuxt-session to build on top of it (: 

Closing this now as local-auth is out of scope of this module. All the best and good luck with your app (:

**Closed by BracketJohn** 2023-02-08 09:26 UTC
Labels: question

**Comment by angelhdzmultimedia** [comment] 2023-02-18 06:34
> Thank you for the nice wishes.
> 
> If you want to start with a local auth strategy, you'lll need another package. You could look into using https://github.com/sidebase/nuxt-session to build on top of it (:
> 
> Closing this now as local-auth is out of scope of this module. All the best and good luck with your app (:

Hello again! I finally had the time to try out the playground. It works like a charm,
and I realized what I meant when I said "Local Strategy" it's the  CredentialsProvider.default with email and password!!!

So I will first make a simple app for register/login, using the default credentials provider, to break the ice and get familiar with this lib, and then will try to get my head around into implementing Steam Auth.

With Passport.js, all I do is pass passport.authenticate() as a route middleware, it redirects to the steam login page, and then return route will have the user property injected in req parameter of the handler.
In Nuxt, we have access to req via event.node. 

The experimentt should be fun, or frustrating haha. Let's see.

And after all, I can always build an express middleware to use Passport.js + Steam Strategy + express-session, for the login with steam api route specifically.
