### ISSUE TITLE
 (AADSTS9002327: Tokens issued for the 'Single-Page Application' client-type may only be redeemed via cross-origin requests.

### ISSUE THREAD

**Issue by SuperMohit** [sidebase/nuxt-auth#301] opened 2023-03-30 11:53 UTC
### Environment

                                                                                         
Nuxt project info:                                                                                                                                      

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.3.2`
- Nitro Version:    `2.3.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `css`, `build`, `runtimeConfig`, `modules`, `auth`
- Runtime Modules:  `@pinia/nuxt@0.4.7`, `@nuxtjs/tailwindcss@6.6.5`, `@sidebase/nuxt-auth@0.4.4`
- Build Modules:    `-`
------------------------------

### Reproduction

```
AzureAD.default(
  
        clientId: '<>',
        tenantId: '<>',
        checks: ['state', 'pkce'],
        client :{
          token_endpoint_auth_method: 'none',
        }
      }),
```

ts config:
```
 auth: {
        enableGlobalAppMiddleware: true
    },
```

### Describe the bug

I am trying to run Oauth Authorization PKCE flow using Azure AD. It seems that Origin is not getting passed. 

 ```
providerId: 'azure-ad',
  message: "invalid_request (AADSTS9002327: Tokens issued for the 'Single-Page Application' client-type may only be redeemed via cross-origin requests.\r\n" +    
    'Trace ID: f1b8b1ee-07ca-4388-bbd5-15e106ad8300\r\n' +
    'Correlation ID: 5428c200-0d73-473f-97e8-0b6919bfb77f\r\n' +
    'Timestamp: 2023-03-30 11:42:27Z)'
```

**Comment by BracketJohn** [comment] 2023-04-03 13:18
Hey @SuperMohit 👋 

I think this is rather related to the way that eith:
- next-auth passes data along,
- you configured the auth flow

rather than this library. Can you checkout the next-auth repo or provide more information that shows how this is related to nuxt-auth? (:

**Comment by BracketJohn** [comment] 2023-04-15 10:46
Hey @SuperMohit 👋 

I'd love to help, but I cannot: Maintaining this library and following down all rabbit-wholes is not possible at the same time. This is why I ask for:
- a reproduction: https://nuxt.com/docs/community/reporting-bugs#create-a-minimal-reproduction
- or that you yourself understand what the problem is first and then report it here or in the next-auth repo (where I guessed above it more likely belongs)

Wish you all the best with figuring out the PKCE-flow, and closing this issue for now. Do feel free to re-open it if you figure out that it is related to nuxt-auth itself, thanks!

**Closed by BracketJohn** 2023-04-15 10:46 UTC
Labels: bug
