### ISSUE TITLE
Refresh() called after page refresh

### ISSUE THREAD

**Issue by ThomasSimonsen20** [sidebase/nuxt-auth#609] opened 2023-12-14 11:01 UTC
First of all thank you for adding the refresh provider, been looking forward to it for a while. :)

After following the refresh provider docs as much as possible, I havn't been able to find anything regarding nuxt-auth to automatically call refresh() after a page refresh.

Current flow I'm testing:

- Login
- Get status with status.value, returns `authenticated`
- Refresh page
- Get status with status.value, returns `unauthenticated`

However if I manually call refresh() after the page refresh it works as expected and status.value returns `authenticated` again.

Is it possible for nuxt-auth to automatically do this?

**Comment by JeppePepp** [comment] 2023-12-20 13:23
Yes agree. Can we please make a fix for this!

**Comment by MrKalten** [comment] 2023-12-20 13:26
I also confirm I have the same problem.

**Comment by JeppePepp** [comment] 2023-12-20 23:09
To add, using 'lax' or 'strict' saves the auth:token to a cookie. If you choose 'none' or false, the auth:token is not saved in the cookie. If you refresh the page when the token is in the cookie, the page crashes.

"[nuxt] [request error] [unhandled] [500] [POST] "https://localhost:7115/api/public/identity/refreshtoken": <no response> fetch failed
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"

**Comment by josip2312** [comment] 2024-01-08 09:59
In this case, what is the solution if the user refreshes for example on a login page, since when the auth middleware checks for authentication, you will still be unauthenticated, the login will happen on manually calling refresh?

**Comment by phoenix-ru** [comment] 2024-02-29 09:59
@ThomasSimonsen20 Could you please provide a minimal reproduction (e.g. by using [Stackblitz Nuxt starter](https://stackblitz.com/fork/github/nuxt/starter/tree/v3-stackblitz))?

The issue you mentioned does not reproduce on `playground-refresh`

**Closed** 2024-03-15 02:01 UTC
Labels: p4, bug, needs-reproduction, provider-refresh, closed-by-bot
