### ISSUE TITLE
Custom fields in session or user

### ISSUE THREAD

**Issue by jorgv** [sidebase/nuxt-auth#148] opened 2023-01-06 12:18 UTC
Hi, opening a new issue since #61 was closed, but I am not sure if it's possible now to inject additional data or not yet, I have been trying to follow the documentation and also the example provided by @JoaoPedroAS51 but nothing seems to work.

In my case I am using the credentials provider, and the big problem for me is where to put the data from backend response to get it in the callbacks.

If I log token, account, profile in the callbacks they seem empty.

![image](https://user-images.githubusercontent.com/32174909/211010753-c60233e7-f0a8-4488-a1b1-0d673e638c65.png)
![image](https://user-images.githubusercontent.com/32174909/211011188-dbbf71f5-7a3e-4a6f-be57-7b4d4377a810.png)

This is the ~/server/api/auth/[...].ts
```
import CredentialsProvider from 'next-auth/providers/credentials'
import { NuxtAuthHandler } from '#auth'

export default NuxtAuthHandler({
  providers: [
    // @ts-expect-error Import is exported on .default during SSR, so we need to call it this way. May be fixed via Vite at some point
    CredentialsProvider.default({
      // The name to display on the sign in form (e.g. 'Sign in with...')
      name: 'Credentials',
      // The credentials is used to generate a suitable form on the sign in page.
      // You can specify whatever fields you are expecting to be submitted.
      // e.g. domain, username, password, 2FA token, etc.
      // You can pass any HTML attribute to the <input> tag through the object.
      credentials: {
        username: { label: 'Username', type: 'text', placeholder: 'jsmith' },
        password: { label: 'Password', type: 'password' },
      },
      profile(profile, tokens) {
        console.log('profile', profile)
        console.log('tokens', tokens)
        return {
          ...profile,
        }
      },

      async authorize(credentials) {
        // You need to provide your own logic here that takes the credentials
        // submitted and returns either a object representing a user or value
        // that is false/null if the credentials are invalid.
        // e.g. return { id: 1, name: 'J Smith', email: 'jsmith@example.com' }
        // You can also use the `req` object to obtain additional parameters
        // (i.e., the request IP address)

        // console.log(credentials)
        // console.log(req.body)
        // const user = { id: '1', name: 'J Smith', email: 'jsmith@example.com' }
        const token = Buffer.from(`${credentials.username}:${credentials.password}`).toString('base64')
        // console.log(token)
        const res = await fetch('http://localhost/backend/login', {
          method: 'post',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Basic ${token}`,
          },
        })
        const data = await res.json()
        // If no error and we have user data, return it
        if (res.ok && res) {
          return {
            name: data.data.user.username,
            email: data.data.user.email,
            image: data.data.token,
            test: 'blah',
            aaa: 'aaa',
          }
        }
        else {
          // If you return null then an error will be displayed advising the user to check their details.
          return null

          // You can also Reject this callback with an Error thus the user will be sent to the error page with the error message as a query parameter
        }
      },
    }),
  ],
  callbacks: {
    // Callback when the JWT is created / updated, see https://next-auth.js.org/configuration/callbacks#jwt-callback
    async jwt({ token, account, profile }) {
      // Persist the OAuth access_token and or the user id to the token right after signin
      console.log('account', account)
      console.log('profile', profile)
      console.log('token', token)
      // if (account) {
      //   token.accessToken = account.token
      //   token.id = profile.id
      // }
      return token
    },
    // Callback whenever session is checked, see https://next-auth.js.org/configuration/callbacks#session-callback
    async session({ session, token, user }) {
      // Send properties to the client, like an access_token and user id from a provider.
      console.log('token', token)
      // session.accessToken = token.accessToken
      // session.user.id = token.id
      return session
    },
  },
})

```

_Originally posted by @jorgv in https://github.com/sidebase/nuxt-auth/issues/61#issuecomment-1373557623_

**Comment by BracketJohn** [comment] 2023-01-11 10:45
Hey @jorgv 👋 

Thanks for moving this here and thus ensuring that our repo is clean (: 

I'll need some further help to assist you:
a) Can you give the `env` output of your setup?
b) can you edit the code so that the console.log output of the different hooks can be differantiated?
c) can you maybe even provide the repo here or to me privately for reproduction?

Thanks!

**Comment by agracia-foticos** [comment] 2023-01-24 07:11
Same issue, we cant modify the user interface!

**Comment by pvlastaridis** [comment] 2023-01-28 15:35
After trying very hard I worked it out as follows:

This is a Strapi Credentials Provider
```
providers: [
    // @ts-ignore Import is exported on .default during SSR, so we need to call it this way. May be fixed via Vite at some point
    CredentialsProvider.default({
      name: "Credentials",
      credentials: {
        // We need the credentials object to be present.
        // You can leave it empty though.
      },
      async authorize(credentials: any) {
        const response = await $fetch<any>(
          `${process.env.STRAPI_BASE_URL}/auth/local/`,
          {
            method: "POST",
            body: JSON.stringify({
              identifier: credentials.username,
              password: credentials.password,
            }),
          }
        ).catch((e) => {
          throw createError({ statusCode: 400, statusMessage: "Bad Request" });
          console.log(e);
        });

        if (response.user) {
          const u = {
            id: response.user.id,
            name: response.user.username,
            email: response.user.email,
            access_token: response.jwt,
          };
          return u;
        } else {
          throw createError({
            statusCode: 403,
            statusMessage: "Credentials not working",
          });
        }
      },
    }),
  ],
  session: {
    strategy: "jwt",
  },
  pages: {
    signIn: "/auth/login",
  },
  callbacks: {
    jwt: async ({token, user, account}) => {
      const isSignIn = user ? true : false;
      if (isSignIn) {
        token.jwt = user.access_token;
        token.id = user.id;
      }
      return Promise.resolve(token);
    },
  },
```
I don't want to call session callback, since this will expose jwt and user id on the frontend through the session object. 

If you insist on doing so, add below callback above jwt callback
   ```
 session: async ({session, token}) => {
      session.jwt = token.jwt;
      session.id = token.id;
      return Promise.resolve(session);
    },
```
Also do not need to use profile function or override the types next-auth.

Using this on a nitro server/api route to call an authenticated rest point on Strapi just as follows:
```
import { getToken, getServerSession } from "#auth";

export default defineEventHandler(async (event) => {
	const  session  =  await  getServerSession(event);
	if (!session) return { status: "unauthenticated!" };  
	
	const token = await getToken({ event });
 
	const settings = {
	    method: "GET",
	    headers: {
		    "Content-Type": "application/json",
		    "Authorization": "Bearer " + token?.jwt
	    },
  };

  const response = await $fetch(
    `${process.env.STRAPI_BASE_URL}/users/me`,
    settings
  );
  return response;
`});`

```

**Comment by pvlastaridis** [comment] 2023-01-28 21:22
This is an improvement passing the role and the user id of the user to the Session Object.

```
// ~/server/api/auth/[...].ts
import CredentialsProvider from "next-auth/providers/credentials";
import { NuxtAuthHandler } from "#auth";

export default NuxtAuthHandler({
  // secret needed to run nuxt-auth in production mode (used to encrypt data)
  secret: process.env.NUXT_SECRET,
  providers: [
    // @ts-ignore Import is exported on .default during SSR, so we need to call it this way. May be fixed via Vite at some point
    CredentialsProvider.default({
      name: "Credentials",
      credentials: {
        // We need the credentials object to be present.
        // You can leave it empty though.
      },
      async authorize(credentials: any) {
        const response = await $fetch<any>(
          `${process.env.STRAPI_BASE_URL}/auth/local/`,
          {
            method: "POST",
            body: JSON.stringify({
              identifier: credentials.username,
              password: credentials.password,
            }),
          }
        ).catch((e) => {
          throw createError({ statusCode: 400, statusMessage: "Bad Request" });
          console.log(e);
        });

        const settings = {
          method: "GET",
          headers: {
            "Content-Type": "application/json",
            Authorization: "Bearer " + response.jwt,
          },
        };
      
        const response2 = await $fetch(
          `${process.env.STRAPI_BASE_URL}/users/me?populate=role`,
          settings
        );
        

        if (response.user) {
          const u = {
            id: response.user.id,
            name: response.user.username,
            email: response.user.email,
            fullname: response.user.name,
            laboratory_name: response.user.laboratory_name,
            laboratory_address: response.user.laboratory_address,
            laboratory_director: response.user.laboratory_director,
            laboratory_city: response.user.Laboratory_city,
            laboratory_telephone: response.user.laboratory_telephone,
            role: (response2 as any).role.type,
            // Passing the original JWT through the jwt field.
            // IMPORTANT: Do not pass decoded JWTs,
            // always make sure they are encoded!
            access_token: response.jwt,
          };
          return u;
        } else {
          throw createError({
            statusCode: 403,
            statusMessage: "Credentials not working",
          });
        }
      },
    }),
  ],
  session: {
    strategy: "jwt",
  },
  pages: {
    signIn: "/auth/login",
  },
  callbacks: {
    // TODO: We will use this trick to add roles to the session
    session: async ({session, token}) => {
      (session as any).role = token.role;
      (session as any).uid = token.id;
      return Promise.resolve(session);
    },
    jwt: async ({token, user}) => {
      const isSignIn = user ? true : false;
      if (isSignIn) {
        token.jwt = user ? (user as any).access_token || '' : '';
        token.id = user ? user.id || '' : '';
        token.role = user ? (user as any).role || '' : '';
      }
      return Promise.resolve(token);
    },
  },
});

```

**Comment by BracketJohn** [comment] 2023-01-30 18:11
Hey everybody 👋 

Thanks for the issue (: 

@pvlastaridis what do you think is still left from your improved version to the final change that this issue needs? Do we need to update this to the docs or edit some exiwsting ones?

**Comment by pvlastaridis** [comment] 2023-01-30 22:35
Yes I think below documents need to be updated. 
https://sidebase.io/nuxt-auth/recipes/custom-session-data
https://sidebase.io/nuxt-auth/recipes/strapi with examples above
No need to add new ones. 
Someone needs also to check https://sidebase.io/nuxt-auth/server-side/jwt-access is still working? If this method works accessToken addition to session should not be mentioned. The Strapi recipe also should not save JWT in the email field. However the example above adding the field ROLE of Strapi it 's certainly a very nice example of a "custom session data".

**Comment by jorgv** [comment] 2023-01-31 11:37
I just want to thank you @pvlastaridis,  finally it works, I felt like nobody understood what was wrong after few issues, it works fantastically. Thanks again!

this resolves #61

**Comment by BracketJohn** [comment] 2023-01-31 16:09
Hey @pvlastaridis, @jorgv 🥇 

Glad that we could finally resolve this for you @jorgv - I agree with the sentiment you shared!

Would you @jorgv or you @pvlastaridis apply the necessary changes / additions to the docs to reflect and resolve the actual problem correctly? I think that would help many other people who have the same problem as you.

The relevant docs are here: https://github.com/sidebase/nuxt-auth/tree/main/docs/content/5.recipes

**Comment by amdp** [comment] 2023-02-11 10:09
Hi there seems to be another non-orthodox workaround that it seemed to me simpler, with no callbacks need, that is giving to data.name the whole user object:

```
//any process you did to get the user information object, then:
if (response.user) {
          const u = {name: {id: user.id, email: user.email, name: user.name, surname: user.surname}}
return u
```

then you can reference it as data.user.name(.id, .name, .whatever) any time you need.

**Closed** 2023-02-15 16:03 UTC
