### ISSUE TITLE
JWE Initialization Vector missing or incorrect type

### ISSUE THREAD

**Issue by LubosAngus** [sidebase/nuxt-auth#371] opened 2023-05-05 18:15 UTC
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.14.0`
- Nuxt Version:     `3.3.3`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@9.3.1`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `typescript`, `modules`, `imports`, `css`, `components`, `auth`, `vite`, `sourcemap`
- Runtime Modules:  `@pinia/nuxt@0.4.8`, `@vueuse/nuxt@9.13.0`, `@sidebase/nuxt-auth@0.5.0`
- Build Modules:    `-`

### Reproduction

Minimal reproduction: https://github.com/LubosAngus/nuxt-auth-bug-reproduction

### Describe the bug

After authorization, I store `accessToken` and `refreshToken` on jwt, based on this example https://authjs.dev/guides/basics/refresh-token-rotation.

I found a pattern, whenever data in auth session cookie is too large _(more than 4kb)_, it will sign me out after refresh, with an error `JWE Initialization Vector missing or incorrect type`.

I think it might be related to this: https://next-auth.js.org/configuration/options#description-12
As stated in there:
> Cookies in NextAuth.js are chunked by default, meaning that once they reach the 4kb limit, we will create a new cookie with the .{number} suffix and reassemble the cookies in the correct order when parsing / reading them.

In my cookies I see cookie that is split into two, that's when this error is appearing. Maybe it's related.
![image](https://user-images.githubusercontent.com/26390734/236535532-9c30f1ea-6620-456f-8749-4a94aaad2327.png)

You can replicate this behaviour in the repository I've included.

---

If you want to see it working properly, just uncomment a return statement inside `/server/api/auth/[...].ts` file, it will not throw an error on refresh. There is just one session cookie, because it's smaller than 4kb.
![image](https://user-images.githubusercontent.com/26390734/236536068-a7d134b3-887e-43e9-aba2-fb72c0fea52c.png)

I don't know, if that error is related to auth cookie being separated into chunks, but that's what I've noticed.

**Comment by kenkichi** [comment] 2023-05-12 00:33
@LubosAngus san

I hav the same issue.
Because the joining order of the split files is not correct, I think you should sort it.

**next-auth/core/lib/cookie.js:**
```
142:    } else {
143:      Object.keys(_cookies).sort().forEach(name => {
144:        if (name.startsWith(cookieName)) (0, _classPrivateFieldGet3.default)(this, _chunks)[name] = _cookies[name];
145:      })
146:    }
```

**Comment by BracketJohn** [comment] 2023-05-14 10:23
Thanks for reporting this, it is actually a duplicate of #293 - let's continue investigation and resolution over there (:

**Closed by BracketJohn** 2023-05-14 10:23 UTC
Labels: bug, duplicate
