### ISSUE TITLE
Vercel deployment - [500] fetch failed

### ISSUE THREAD

**Issue by maliksvd** [sidebase/nuxt-auth#279] opened 2023-03-08 15:12 UTC
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.3`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `app`, `build`, `modules`, `nitro`, `content`, `auth`, `i18n`, `colorMode`, `css`, `postcss`, `vite`
- Runtime Modules:  `@sidebase/nuxt-auth@0.4.3`, `@nuxtjs/i18n@8.0.0-beta.9`, `nuxt-icon@0.3.2`, `@nuxt/content@2.4.3`, `@nuxtjs/color-mode@3.2.0`, `@nuxt/image-edge@1.0.0-27919678.2f5b64b`, `nuxt-simple-sitemap@1.0.7`
- Build Modules:    `-`

### Reproduction

Using GoogleProvider and deployed on Vercel.

### Describe the bug

I got 2 errors logs:

[500] fetch failed and [ERR_MODULE_NOT_FOUND] for a deployment on Vercel.

Working well on local but on Vercel, i got these errors.

### Additional context

**.env** 
ORIGIN="http://localhost:3000"

**nuxt.config.ts** 
auth: { origin: process.env.ORIGIN, basePath: '/api/auth' },

**server/api/auth/[...].ts** 
import GoogleProvider from 'next-auth/providers/google'
import { NuxtAuthHandler } from '#auth'

export default NuxtAuthHandler({
  pages: {
    signIn: '/login',
  },
  secret: process.env.NUXT_SECRET,
  providers: [
    GoogleProvider.default({
      clientId: 'XXXXXXXXX',
      clientSecret: 'XXXXXXXXXXX',
    }),
  ],
})

### Logs

```shell
[log] [nitro]   ├─ /api/og/cache.1678287214165.json (45ms) 
[error] [nuxt] [request error] [unhandled] [500] fetch failed (http://localhost:300/api/auth/session?callbackUrl=http://localhost/)

And on Vercel Logs

2023-03-08T15:05:27.991Z	undefined	ERROR	Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/node_modules/unstorage/drivers/overlay.mjs' imported from /var/task/index.mjs
    at new NodeError (node:internal/errors:400:5)
    at finalizeResolution (node:internal/modules/esm/resolve:331:11)
    at moduleResolve (node:internal/modules/esm/resolve:994:10)
    at moduleResolveWithNodePath (node:internal/modules/esm/resolve:938:12)
    at defaultResolve (node:internal/modules/esm/resolve:1202:79)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:842:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
RequestId: bc0cfb6b-bfcb-4b47-9377-895d72d9327a Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

**Comment by hi-reeve** [comment] 2023-03-13 03:08
duplicate of #265

**Closed** 2023-03-13 09:58 UTC
Labels: bug
