### ISSUE TITLE
Pressing back button after signOut() shows user a globally protected page

### ISSUE THREAD

**Issue by JamesZeki** [sidebase/nuxt-auth#696] opened 2024-02-29 17:39 UTC
### Environment

- Operating System: Linux
- Node Version:     v20.11.1
- Nuxt Version:     3.10.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.4
- Builder:          -
- User Config:      devtools, css, postcss, runtimeConfig, modules, auth
- Runtime Modules:  @sidebase/nuxt-auth@0.6.7
- Build Modules:    -

### Reproduction

It happens from the demo website github: https://github.com/sidebase/nuxt-auth-example/issues

### Describe the bug

It happens on the demo website: https://nuxt-auth-example.sidebase.io/

If you go to the globally protected page: https://nuxt-auth-example.sidebase.io/protected/globally

You cannot access it, however. If you: login > logout > press back button -- you can see the page even though you have just logged out. Only when a refresh happens do you get kicked out by the middleware. This happens locally as well when I try it.

**Comment by zoey-kaiser** [comment] 2024-03-01 07:59
Duplicate of https://github.com/sidebase/nuxt-auth/issues/548

**Closed** 2024-03-01 08:00 UTC
Labels: p4, bug
