### ISSUE TITLE
How to mock useSession composable

### ISSUE THREAD

**Issue by th1nkgr33n** [sidebase/nuxt-auth#107] opened 2022-12-12 14:41 UTC
### Ask your question

Hey folks,

I got a nuxt3 project and due to the fact that the nuxt-community/auth-module is not yet migrated for nuxt3, we try out your solution.
The integration itself works, but when it comes to test I got headache.
I'm not the biggest professional for testing with vitest or jest, but in the end I found no solution thats why I asked for help.

I tried several approaches to mock useSession, but non of them helped, or maybe I misconfigured them
Someone has a clue how to mock it and help me out?

### Additional information

My project:
- node 18
- nuxt-3
- @sidebase/nuxt-auth
- vitest
- pnpm

Here is my component which should just render the header bar with Buttons and logged in username
```js
<template>
  <header>
      <div class='flex'>
        <MyLogo />
        <div v-if="!isEmptyObject(session)">
          <p class='text-white mr-3'>{{ session?.user?.name }}</p>
        </div>
        <Button v-if="!isEmptyObject(session)" @click="signOut()"  />
        <Button v-else @click="signIn('myProvider', { callbackUrl: '/dashboard' })"  />
      </div>
  </header>
</template>

<script setup lang='ts'>
const { signIn, signOut, getSession } = useSession()
const session = await getSession()
</script>
```

When I run the tests I got this:
_ReferenceError: useSession is not defined_

Here is how my TheHeader.test.ts looks like
```
import { render } from '@testing-library/vue'
import TheHeader from '~/components/TheHeader.vue'

describe('App', () => {
  test('should render MyLogo correctly', async () => {
    const { getByTestId } = render(TheHeader)
    expect(getByTestId('logo')).toBeInTheDocument()
  })
})
```

**Comment by BracketJohn** [comment] 2022-12-13 15:23
This is rather a nuxt-problem than a `nuxt-auth` problem I believe, see for exaqmple here: https://github.com/nuxt/framework/discussions/5897

The problem is that `vitest` / `jest` don't natively auto-import the composables like nuxt does it when you run `npm run dev`.

To resolve this, you can manually add the import of the composable as shown in above link. This has also been a hassle for us in the past, but there's sadly nothing we can do about it until `nuxt` comes forward with better testing support. I believe this is one of the prio items of them for the next release(s).

Closing this issue now as there's nothing more to do. Feel free to add another questions / open a new issue if there's anything else!

**Closed by BracketJohn** 2022-12-13 15:23 UTC
Labels: question
