### ISSUE TITLE
how to custom session field and user field? (CredentialsProvider) [ts language]

### ISSUE THREAD

**Issue by chanthavong** [sidebase/nuxt-auth#61] opened 2022-11-26 05:01 UTC
### Describe the feature

Hi, i'm read doc & try  set custom session field and user field 

i want set some field in user

```js
{
  accessToken: 'dddddddLZ_pCi1bLqdac3sdfdsfdsfdsfdsf6Jxlw0VyVCzHDopjXuYAviolnA',
  accessTokenExpiresIn: 604800,
  refreshToken: '7c43400b-xxxx-xxxx-xxxx-99b0f91bd570',
  user: {
    id: '7c43400b-xxxx-xxxx-xxxx-99b0f91bd570',
    createdAt: '2021-05-19T17:24:50.579279+07:00',
    displayName: 'test',
    avatarUrl: 'https://s.gravatar.com/avatar/ac44930a62044d038e16f027629b9206?r=g&default=blank',
    locale: 'en',
    email: 'example@gmail.com',
    isAnonymous: false,
    defaultRole: 'admin',
    metadata: { permissions: ['xx'] },
    emailVerified: true,
    phoneNumber: null,
    phoneNumberVerified: false,
    activeMfaType: null,
    roles: [ 'me', 'user' ]
  }
}

```

**Comment by BracketJohn** [comment] 2022-11-29 09:07
Hey @chanthavong!

Thanks for the question! I think that this is a common one, so we shuould document it in the docs. Have you already found a solution for this in the meantime? (: Maybe we can then use yours.

Otherwise, I would follow the next auth docs on this one.

**Comment by JoaoPedroAS51** [comment] 2022-11-29 14:38
@BracketJohn @chanthavong Hey! You can do this by creating a `d.ts` file and declaring `Session` interface. See more at https://next-auth.js.org/getting-started/typescript#module-augmentation

```ts
// file: ~/types/next-auth.d.ts
declare module "next-auth" {
  interface Session {
    accessToken: string
    accessTokenExpiresIn: number
    refreshToken: string
    user: {
      id: string
      ...
    }
  }
}
```

**Comment by BracketJohn** [comment] 2022-11-29 16:01
Thanks @JoaoPedroAS51 ❤️ 

This then augments the type interface, which callback / method would you hook into to then return that additional data? I think this is also part of the problem of @chanthavong. Already very helpful though 🪨

**Comment by JoaoPedroAS51** [comment] 2022-11-29 16:45
Oh I see, my bad. I read "ts" and misunderstood the question. So, to extend the session with `accessToken` for example, you must add `jwt` and `session` callbacks. And to define the user object, add `profile` callback to you provider. Something like this:

```ts
// file: ~/server/api/auth/[...].ts
export default NuxtAuthHandler({
  ...
  providers: [
    CredentialsProvider({
      ...
      // Here you define user object
      profile(profile, tokens) {
        return {
           ...
        }
      },
    })
  ],
  callbacks: {
   // Props defined here can be accessed in session callback and will be returned by getToken
    jwt: ({ token, account, user }) => {
      if (account && user) {
        token.accessToken = account.access_token
        // The `user` is the data defined in `profile` callback
        token.user = user
      }

      return token
    },
    
    // Session retuned by useSession and getSession
    session: ({ token, session }) => {
      if (token) {
        session.user = token.user
        session.accessToken = token.accessToken
      }

      return session
    },
  },
})
```

```ts
// file: ~/types/next-auth.d.ts
import type { User } from 'next-auth'

declare module 'next-auth' {
  /*
   * Returned by useSession and getSession
   */
  interface Session extends DefaultSession {
    accessToken: string
    user: {
      ...
    }
  }

  /*
   * Usually contains information about the provider being used
   * and also extends TokenSet, which is different tokens returned by OAuth Providers.
   */
  interface Account {
    ...
    access_token: string
  }
}

declare module 'next-auth/jwt' {
  /** Returned by the jwt callback and getToken, when using JWT sessions */
  interface JWT {
    ...
    accessToken: string
    user: User
  }
}
```

**Note:** This is not a complete example. And to implement refresh token you shoud read https://next-auth.js.org/tutorials/refresh-token-rotation

I'm new to next-auth and this is what I tested with KeycloakProvider, but I believe it will work for CredentialsProvider too.

**Comment by blumewas** [comment] 2022-11-30 13:58
Hi,

I have tried your config for Laravel Sanctum. I have created a `~/types/next-auth.d.ts` file and added the keys from my endpoint. When I log the data It does not seem that my file is used. E.g. the output for session inside the token callback is always 

```
{
  user: { name: undefined, email: undefined, image: undefined },
  expires: 'next month'
}
```
Also inside token I have a key called `user` with the values returned by my authorize callback.

Am I missing something?

**Comment by BracketJohn** [comment] 2022-12-08 10:12
Hey @blumewas!

Thanks for the question, sorry for taking some time to get around to it. Have you also changed the `NuxtAuthHandler` callbacks as outlined by @JoaoPedroAS51 above to return more data?

**Comment by BracketJohn** [comment] 2022-12-08 11:46
FYI: #90 will also add a Recipe section that contains the proposal by @JoaoPedroAS51 in a more guiding format. Check it out at https://sidebase.io/nuxt-auth/recipes/custom-session-data once #90 is merged

**Comment by noook** [comment] 2022-12-18 15:54
The signature for `useSession` does not go alone this answer :(

![image](https://user-images.githubusercontent.com/19751938/208307447-e871e0f9-c6e4-40b8-8749-ae516d868406.png)

`useSession().data` does not refer to next-auth types so overriding it does not help much when using the type outside of the NuxtAuth handler

**Comment by BracketJohn** [comment] 2022-12-19 08:25
Oh damn - yeah, that's unfortunate. We'll look into this and improve it! I've opened #112 to work on this.

And I will close this issue now, as the original author does not respond anymore. Let's continue discussion on the typing in #112

**Closed by BracketJohn** 2022-12-19 08:25 UTC
Labels: question

**Comment by jorgv** [comment] 2023-01-06 12:17
Hi, sorry for reopening this issue, but I am not sure if it's possible now to inject additional data or not yet, I have trying to follow the documentation and also the example provided by @JoaoPedroAS51 but nothing seems to work.

In my case I am using the credentials provider, and the big problem for me is where to put the data from backend response in order to get it in the callbacks.

If I log token, account, profile in the callbacks they seem empty.

![image](https://user-images.githubusercontent.com/32174909/211010753-c60233e7-f0a8-4488-a1b1-0d673e638c65.png)
![image](https://user-images.githubusercontent.com/32174909/211011188-dbbf71f5-7a3e-4a6f-be57-7b4d4377a810.png)


This is the ~/server/api/auth/[...].ts
```
import CredentialsProvider from 'next-auth/providers/credentials'
import { NuxtAuthHandler } from '#auth'

export default NuxtAuthHandler({
  providers: [
    // @ts-expect-error Import is exported on .default during SSR, so we need to call it this way. May be fixed via Vite at some point
    CredentialsProvider.default({
      // The name to display on the sign in form (e.g. 'Sign in with...')
      name: 'Credentials',
      // The credentials is used to generate a suitable form on the sign in page.
      // You can specify whatever fields you are expecting to be submitted.
      // e.g. domain, username, password, 2FA token, etc.
      // You can pass any HTML attribute to the <input> tag through the object.
      credentials: {
        username: { label: 'Username', type: 'text', placeholder: 'jsmith' },
        password: { label: 'Password', type: 'password' },
      },
      profile(profile, tokens) {
        console.log('profile', profile)
        console.log('tokens', tokens)
        return {
          ...profile,
        }
      },

      async authorize(credentials) {
        // You need to provide your own logic here that takes the credentials
        // submitted and returns either a object representing a user or value
        // that is false/null if the credentials are invalid.
        // e.g. return { id: 1, name: 'J Smith', email: 'jsmith@example.com' }
        // You can also use the `req` object to obtain additional parameters
        // (i.e., the request IP address)

        // console.log(credentials)
        // console.log(req.body)
        // const user = { id: '1', name: 'J Smith', email: 'jsmith@example.com' }
        const token = Buffer.from(`${credentials.username}:${credentials.password}`).toString('base64')
        // console.log(token)
        const res = await fetch('http://localhost/backend/login', {
          method: 'post',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Basic ${token}`,
          },
        })
        const data = await res.json()
        // If no error and we have user data, return it
        if (res.ok && res) {
          return {
            name: data.data.user.username,
            email: data.data.user.email,
            image: data.data.token,
            test: 'blah',
            aaa: 'aaa',
          }
        }
        else {
          // If you return null then an error will be displayed advising the user to check their details.
          return null

          // You can also Reject this callback with an Error thus the user will be sent to the error page with the error message as a query parameter
        }
      },
    }),
  ],
  callbacks: {
    // Callback when the JWT is created / updated, see https://next-auth.js.org/configuration/callbacks#jwt-callback
    async jwt({ token, account, profile }) {
      // Persist the OAuth access_token and or the user id to the token right after signin
      console.log('account', account)
      console.log('profile', profile)
      console.log('token', token)
      // if (account) {
      //   token.accessToken = account.token
      //   token.id = profile.id
      // }
      return token
    },
    // Callback whenever session is checked, see https://next-auth.js.org/configuration/callbacks#session-callback
    async session({ session, token, user }) {
      // Send properties to the client, like an access_token and user id from a provider.
      console.log('token', token)
      // session.accessToken = token.accessToken
      // session.user.id = token.id
      return session
    },
  },
})

```

**Comment by BracketJohn** [comment] 2023-01-11 10:44
-> moved discussion to #148

**Comment by bargar** [comment] 2023-01-19 19:14
For folks finding this issue via search, here's relevant docs:

https://sidebase.io/nuxt-auth/recipes/custom-session-data

**Comment by jorgv** [comment] 2023-01-23 09:28
the problem is that following those docs doesn't work as shown here #148

**Comment by makeitflow** [comment] 2023-03-16 00:30
Not working for me either

**Comment by jorgv** [comment] 2023-03-16 15:44
@makeitflow  the documentation is updated, and it works fine, what doesn't work for you?

https://sidebase.io/nuxt-auth/recipes/custom-session-data

**Comment by andreasvirkus** [comment] 2023-12-08 08:41
I've followed the steps in the guide and while I do now have the new data under `session.id`, TypeScript is still unaware of it and displays the default types (`{ name, email, image }`, whereas it should show `{ id, name, email, avatar }`)

Here's my NuxtAuthHandler in `[...].ts`

```js
export default NuxtAuthHandler({
  secret: process.env.AUTH_SECRET,
  pages: {
    signIn: '/',
  },
  providers: [
    // @ts-expect-error You need to use .default here for it to work during SSR. May be fixed via Vite at some point
    SlackProvider.default({
      clientId: process.env.SLACK_CLIENT_ID,
      clientSecret: process.env.SLACK_CLIENT_SECRET,
      async authorize(credentials: any) {
        if (credentials) {
          const user = await getMe({ email: credentials.user.email })
          const u = {
            id: user.id,
            name: credentials.user.name,
            email: credentials.user.email,
            image: credentials.user.picture,
          }

          return u
        } else {
          throw createError({
            statusCode: 403,
            statusMessage: 'Credentials not working',
          })
        }
      },
    }),
  ],
  callbacks: {
    // Callback when the JWT is created / updated, see https://next-auth.js.org/configuration/callbacks#jwt-callback
    jwt: async ({ token }) => {
      token.user = await getMe({ email: token.email || '' })

      if (!token.user) return Promise.reject(token)
      return Promise.resolve(token)
    },
    // Callback whenever session is checked, see https://next-auth.js.org/configuration/callbacks#session-callback
    session: async ({ session, token }) => {
      ;(session as any).role = token.role
      ;(session as any).uid = token.id
      ;(session as any).user = token.user
      return Promise.resolve(session)
    },
  },
})

```
