### ISSUE TITLE
How to use it with Laravel Passport ?

### ISSUE THREAD

**Issue by trijayadigital** [sidebase/nuxt-auth#149] opened 2023-01-09 00:56 UTC
### Ask your question

I need to integrate it with Laravel Passport (password grant type) like the older version of nuxt auth because i want to use it in the first-party app workflow. How to do this ? Should i use credentials or oauth ?

**Comment by BracketJohn** [comment] 2023-01-11 10:58
Hey!

If you're using the password grant-type you'll have to implement the API interactions by yourself withing the credentials provider. An example of this for strapi can be seen here: https://sidebase.io/nuxt-auth/recipes/strapi

If you were to use the oauth-flow you could create your custom laravel passport oauth config like so: https://github.com/sidebase/nuxt-auth/issues/118#issue-1506234552

**Comment by Jericho1060** [comment] 2023-01-12 11:19
Laravel passport is providing a standard Oauth2 authentication using client id, client secret and redirect uri.
you can create a client with a single artisan command

Then you can use the custom Oauth provider, see: https://next-auth.js.org/configuration/providers/oauth#using-a-custom-provider

**Comment by timothymarois** [comment] 2023-02-04 20:43
This package still doesn't work with laravel after trying many modifications. Credentials or OAUTH. If there is a way to set it up, there needs to be instructions given its the most popular PHP framework. Been trying to get auth working on UI domain and API domain for years, always having to come up with a hack. We need to bridge the gap of this confusion.

**Comment by BracketJohn** [comment] 2023-02-08 10:15
Hey y'all 👋 

Sorry for the frustration - the problem is that I don't have a PHP setup to test, verify, ... these changes. I could support though if one of you creates a repo that should work + instructions on how to use it.

If somebody provides this I would be very happy to invest time, go through it step by step and figure out how it works + then document it in a recipe. As @Jericho1060 pointed out I would expect this to work quite well, as this is a standard oauth2 setup.

@timothymarois maybe you want to open a repo and we iterate together? 

Or even better @Jericho1060 you seem to have figured this out already: Can you show how you did it, so that others like @timothymarois can profit from it?

**Comment by Jericho1060** [comment] 2023-02-08 14:26
@BracketJohn I made it in the past, but I'm not anymore working on the project, I'll when I have time to create a simple sample with OAuth2 and Laravel passport. But it won’t be immediately

**Comment by BracketJohn** [comment] 2023-02-08 15:32
Thanks 🙇 If you have just the code snippet to share handy, you can already do that (:

**Comment by Jericho1060** [comment] 2023-02-08 15:53
@BracketJohn nah, actually, I don't have access anymore to the source. But it's currently not a lot of work, I'm still working with Laravel for a project, so I have all my dev env ready on that side, just have to rework the Nuxt part.

**Comment by BracketJohn** [comment] 2023-02-08 16:42
Ah gotcha! Sounds great - looking forward to seeing it work out - I'm sure @timothymarois and others would be super happy ❤️

**Comment by Jericho1060** [comment] 2023-02-10 14:17
@BracketJohn and @timothymarois here an example of a working connector with Laravel Passport (Latest version)

```typescript
// ~/server/api/auth/[...].ts

import {NuxtAuthHandler} from '#auth'

//replace that with env variables // runtime config
const APP_BASE_URL = 'http://www.my_passport_app.test/'
const CLIENT_ID = '1234567890'
const CLIENT_SECRET = '1234567890'

export default NuxtAuthHandler({
    secret: "MySecretKey", //replace that with env variables // runtime config
    providers: [
        {
            id: "laravelpassport", //ID is only used for the callback URL
            name: "Passport", //Name is used for the login button
            type: "oauth",
            version: "2.0",
            authorization: {
                url: `${APP_BASE_URL}/oauth/authorize`,
                params: {
                    scope: "*", //this is the wildcard for all scopes in laravel passport, you can specify scopes separated by a space
                }
            },
            token: {
                url: `${APP_BASE_URL}/oauth/token`,
            },
            clientId: CLIENT_ID,
            clientSecret: CLIENT_SECRET,
            userinfo: {
                url: "http://www.e-formadapt.test/api/v1/me",//this is a custom route that must return the current user that must be created in laravel
            },
            profile: (profile) => {
                //map the session fields with you laravel fields
                //profile is the user coming from the laravel app
                //update the return with your own fields names
                return {
                    id: profile.id,
                    name: profile.name,
                    email: profile.email,
                    image: profile.image,
                };
            },
            idToken: false,
        }
    ],
});
```

**Comment by zoey-kaiser** [comment] 2023-02-20 13:42
Hi @Jericho1060! Thank you for the snippet. I think it would be super useful to add your snippet to the [recipes](https://sidebase.io/nuxt-auth/recipes) page of the docs. 

Do you want to do this or should I put it on my list? You can add a new page right here: https://github.com/sidebase/nuxt-auth/tree/main/docs/content/5.recipes. Have a look at the other recipes for inspiration!

Ill close this issue for now. If anything else comes up feel free to open a new one and Thank you again for your great investigation 💪

**Closed by zoey-kaiser** 2023-02-20 13:42 UTC
Labels: question

**Comment by Jericho1060** [comment] 2023-02-20 14:43
@zoey-kaiser sure, i'll have a look to add something more complete to the recipes during the week, i'll ask you if i have any trouble doing it

**Comment by zoey-kaiser** [comment] 2023-02-20 15:10
> @zoey-kaiser sure, i'll have a look to add something more complete to the recipes during the week, i'll ask you if i have any trouble doing it

@Jericho1060 Sounds amazing! I really appreciate your contribution ❤️

**Comment by Jericho1060** [comment] 2023-03-02 13:58
@zoey-kaiser sorry for the delay, I just created the PR for the documentation

**Comment by juandelperal** [comment] 2023-04-12 13:34
Thanks for the guide!
After logging in, how can I get the full access token to make further requests to the API? 

Is it a good idea to make a proxy that intercepts local requests to the laravel servers adding a header like
`Authorization: Bearer ...`

or is there a better way to do this?

Thanks in advance!

**Comment by Asxer** [comment] 2023-05-23 20:05
Excuse me, but what does `[...].ts` means? Is it how the file should be named?

**Comment by zoey-kaiser** [comment] 2023-05-23 20:07
> Excuse me, but what does `[...].ts` means? Is it how the file should be named?

@Asxer yes! It catches all the incoming requests going to `/api/auth` so you don't need to define it for every single route!

**Comment by Jericho1060** [comment] 2023-05-23 20:07
> Excuse me, but what does `[...].ts` means? Is it how the file should be named?

It's the real file name. It's a wild card for all routes, that's a basic concept of nuxt.

**Comment by asokr** [comment] 2023-06-23 14:14
Thanks for the guide, but I'm having trouble logging in. Could you please tell me why http://localhost:3000/api/auth/signin/laravelpassport might be returning a 500 error?

**Comment by Jericho1060** [comment] 2023-06-23 14:30
@asokr we cannot really help you on that, if it's returning an error 500, it's that you have an error on the laravel side

**Comment by Jericho1060** [comment] 2023-06-23 14:31
also, you may have an error message with the error code

**Comment by hadimajidi** [comment] 2023-08-16 18:13
> @BracketJohn and @timothymarois here an example of a working connector with Laravel Passport (Latest version)
> 
> ```ts
> // ~/server/api/auth/[...].ts
> 
> import {NuxtAuthHandler} from '#auth'
> 
> //replace that with env variables // runtime config
> const APP_BASE_URL = 'http://www.my_passport_app.test'
> const CLIENT_ID = '1234567890'
> const CLIENT_SECRET = '1234567890'
> 
> export default NuxtAuthHandler({
>     secret: "MySecretKey", //replace that with env variables // runtime config
>     providers: [
>         {
>             id: "laravelpassport", //ID is only used for the callback URL
>             name: "Passport", //Name is used for the login button
>             type: "oauth",
>             version: "2.0",
>             authorization: {
>                 url: `${APP_BASE_URL}/oauth/authorize`,
>                 params: {
>                     scope: "*", //this is the wildcard for all scopes in laravel passport, you can specify scopes separated by a space
>                 }
>             },
>             token: {
>                 url: `${APP_BASE_URL}/oauth/token`,
>             },
>             clientId: CLIENT_ID,
>             clientSecret: CLIENT_SECRET,
>             userinfo: {
>                 url:`${APP_BASE_URL}/api/v1/me`",//this is a custom route that must return the current user that must be created in laravel
>             },
>             profile: (profile) => {
>                 //map the session fields with you laravel fields
>                 //profile is the user coming from the laravel app
>                 //update the return with your own fields names
>                 return {
>                     id: profile.id,
>                     name: profile.name,
>                     email: profile.email,
>                     image: profile.image,
>                 };
>             },
>             idToken: false,
>         }
>     ],
> });
> ```
> 
> **Edit** Don't forget to add the callback url to the passport client config: `http://localhost:3000/api/auth/callback/laravelpassport`

Where should this be added?
Edit
Don't forget to add the callback url to the passport client config: http://localhost:3000/api/auth/callback/laravelpassport
could you please give the right palce? should this be added to [...].ts?

**Comment by gilles6** [comment] 2024-05-14 14:25
@juandelperal I have the same issue, did you find a way to get the user token provided by Laravel ? Or is there any specific way to make further request to the Laravel API?

**Comment by gilles6** [comment] 2024-06-06 16:14
@hanier10 Thanks for your reply, however you're using password grant type which is no longer recommended.
- https://laravel.com/docs/11.x/passport#password-grant-tokens
- https://oauth.net/2/grant-types/password/

**Comment by franck-grenier** [comment] 2025-02-07 16:51
Hello,
this issue is really interesting for me as I need to authenticate my Nuxt 3 app users on a Laravel Passport, through Oauth2 **with PKCE flow**.

Is it possible to plug PKCE flow in that kind of "custom auth handler" ?
