### ISSUE TITLE
Redirect to default provider's login page immediately

### ISSUE THREAD

**Issue by flangam** [sidebase/nuxt-auth#244] opened 2023-02-16 05:04 UTC
### Ask your question

How do I make a protected page redirect to the provider's login page directly and not to the provider selection page?  For example, I'm not yet authenticated and I will just enter a protected page in the browser like http://localhost:5000/profile.  Since I only have 1 provider, I want to be redirected immediately to the login page without having the following page show up first.

<kbd>![provider_select](https://user-images.githubusercontent.com/7723805/219270985-3fb83602-5b7a-440e-bf46-12266aa21580.png)</kbd>

Currently, my `..\server\api\auth\[...].ts` is configured as:

```
import KeycloakProvider from 'next-auth/providers/keycloak'
import { NuxtAuthHandler } from "#auth"

export default NuxtAuthHandler({
    // secret needed to run nuxt-auth in production mode (used to encrypt data)
    secret: process.env.NUXT_SECRET,
    providers: [
        KeycloakProvider.default({
            clientId: process.env.AUTH_CLIENT_ID,
            clientSecret: process.env.AUTH_CLIENT_SECRET,
            issuer: process.env.AUTH_ISSUER
        })
    ]
})
```

Also, I have enabled the global authentication middleware in `nuxt.config.ts`

```
// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  modules: ['@sidebase/nuxt-auth'],
  auth: {
    origin: process.env.ORIGIN,
    enableGlobalAppMiddleware: true
  }
})
```

**Comment by BracketJohn** [comment] 2023-02-16 08:24
Set the `defaultProvider` option, see https://sidebase.io/nuxt-auth/configuration/nuxt-config

Does that resolve your question? (:

**Comment by glennovische** [comment] 2023-03-14 10:06
Im also having this issue + does this package use a BEARER token?

**Comment by victorlmneves** [comment] 2023-03-21 17:20
Also trying to achieve the same behaviour but in my case I'm using Auth0

**Comment by victorlmneves** [comment] 2023-03-31 08:57
I manage it to work (not 100%)
In my case, the problem looks like it's related to project settings on Auth0 as when I tested it with an Auth0 personal account it worked automatically showing the custom login page from Auth0, but the logout is not working as expected as I see a cookie being deleted but then when accessing a protected route again I get automatically logged in (even deleting all cookies)

**Comment by BracketJohn** [comment] 2023-04-03 13:53
Can one of you please provide a reproduction of this?

**Comment by BeSaad** [comment] 2023-04-11 22:24
Same issue here, in the console I see this error : 
```
[nuxt] [request error] [unhandled] [500] The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of URLSearchParams
  at new NodeError (node:internal/errors:399:5)  
  at Function.from (node:buffer:326:9)  
  at readRawBody (./node_modules/h3/dist/index.mjs:280:53)  
  at readBody (./node_modules/h3/dist/index.mjs:306:22)  
  at readBodyForNext (./.nuxt/dev/index.mjs:433:18)  
  at getInternalNextAuthRequestData (./.nuxt/dev/index.mjs:516:24)  
  at ./.nuxt/dev/index.mjs:528:31  
  at ./node_modules/h3/dist/index.mjs:1189:14  
  at Object.handler (./node_modules/h3/dist/index.mjs:1432:12)  
  at Object.handler (./node_modules/h3/dist/index.mjs:1247:31)
```

**Comment by BracketJohn** [comment] 2023-04-11 22:36
Thanks, however: Still needs a reproduction, please provide one so that we can sctually help. Without one, we will close this issue at some point. Thanks!

**Comment by flangam** [comment] 2023-04-12 00:50
@BracketJohn 

Reproduction steps for me:

1. Clear previous authentication
    - Open the URL at **< root URL of identity provider or auth issuer >/.well-known/openid-configuration** and copy the value of the **end_session_endpoint**.  Open the URL to logout your previous session.  (Note: Some identity providers require you to provide other parameters to logout your session successfully.  Please check with them.  I'm using Azure AD authentication now and you just have to follow the steps shown on the browser to logout from your session.)
    - Clear browser cache.  If you can't do this because there are other open applications, simply remove the cookies and other site data of your application (localhost or some other remote server) and the cookies and other site data of the identity provider or auth issuer.
2. Open a page in your application that requires the user to be authenticated.  In my case, I have profile page that should display the user's details taken from the token claims.  For example, http://localhost:5000/profile

I now have this in my browser:
<kbd>![image](https://user-images.githubusercontent.com/7723805/231318953-48614a8d-0d64-46c6-a9e0-4b15b485cbd8.png)</kbd>


And these are the logs:
![image](https://user-images.githubusercontent.com/7723805/231318856-2dc85b14-c916-42f7-ba47-e2ef64b58e18.png)

I hope this helps.

**Comment by flangam** [comment] 2023-04-13 01:49
@BracketJohn 

I am testing the application at StackBlitz:
<kbd>![image](https://user-images.githubusercontent.com/7723805/231624413-28ea3692-49b2-4a7d-b636-f68e187adc3c.png)</kbd>

But after clicking **Log In**, I got this:
<kbd>![image](https://user-images.githubusercontent.com/7723805/231624636-e475f912-cc62-48d6-94da-b67069faafd2.png)</kbd>

Do I need to make additional configuration to make it run in StackBlitz?  This is working in my local.

**Comment by BracketJohn** [comment] 2023-04-15 10:49
Hey @flangam 👋 

Stackblitz has problems with cookies which makes using nuxt-auth hard to impossible as it relies on cookies. See here e.g., for the info about cookies: https://github.com/nuxt/nuxt/issues/20030#issuecomment-1493346372

Please test it locally / on a server and then provide a minimal reproduction repository that I am able to run locally (see https://nuxt.com/docs/community/reporting-bugs#create-a-minimal-reproduction) so that we can continue debugging here. Until then I'll close this issue. As said: re-open it with a reproduction or pose a new issue if you've figured out further details. Thanks!

**Closed by BracketJohn** 2023-04-15 10:49 UTC
Labels: question

**Comment by flangam** [comment] 2023-04-16 17:56
@BracketJohn

GitHub repo at: https://github.com/flangam/nuxt-auth-bug-reproduction

Notes are in README.md

**Comment by BracketJohn** [comment] 2023-04-17 09:02
The login auth demo works for me locally + you can verify it in the deployed version as well (see link in repo), so, unsure how to proceed from this, sorry ❤️‍🩹

**Comment by BrahimMasmoudi** [comment] 2023-07-18 09:27
Hello, is there any solution found for this issue please ? thank you

**Comment by flangam** [comment] 2023-07-18 10:31
@BrahimMasmoudi There's a sense of unwillingness to address this issue.  That's the impression I got even after providing the codes to reproduce the issue.
